### ISSUE TITLE
Neveikianti nuoroda „Puikiai įvertinto darbo pavyzdys“

### ISSUE THREAD

**Issue by vakaras** [LIKS/latex#1]
Perskaičius šį sakinį, susidaro įspūdis, kad „Puikiai įvertinto darbo pavyzdys, jo PDF.“ nuoroda „pavyzdys“ turėtų rodyti į išeities tekstus, o „PDF“ į PDF failą. Tačiau, nuoroda „pavyzdys“ niekur neveda:

```
<a href="#"><b>pavyzdys</b></a>
```

**Comment by strazdas** [comment]
Problema pataisyta. Visas nuorodas, kurių turinio neturėjau (nebuvau sutvarkęs) nurodžiau į niekur (href="#"). Kol kas paruošiau ir nurodžiau tik magistrinio darbo šabloną bei pavyzdžio LaTeX išeities failus. Dar trūksta: kursinio darbo, bakalaurinio bei VU skaidrių šablonų.
