### ISSUE TITLE
latex.liks.lt puslapyje nurodytame diegime trūksta fonts-texgyre

### ISSUE THREAD

**Issue by carl-di-ortus** [LIKS/latex#18]
Nurodyta komanda `sudo apt-get install texlive-full biber` yra nepakankama ir `make` komanda pakimba kompiliuodama VUMIFPSbakalaurinis.cls failą 28 eilutėje.
Įrašius `fonts-texgyre` paketą `make` komanda suveikia be problemų.

Naudojama debian testing, be rekomendacinių instaliavimų, t.y. su nustatymu:
echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf

**Comment by niekas** [comment]
Ačiū už Jūsų pastabas! Tuoj pat papildysiu šablonus ir informaciją latex.liks.lt puslapyje (:
Džiaugiuosi, kad pasirinkote naudoti LaTeX baigiamojo darbo rašymui (:

**Comment by niekas** [comment]
Pataisyta. Reikiamus paketus taip pat galima įsidiegti projekto direktorijoje įvykdžius `make ubuntu` komandą (nežinau koks komandas pavadinimas tinka tiek Debian, tiek Ubuntu).
