### ISSUE TITLE
Nėra Bakalaurinio ir Kursinio darbų LaTeX šablonų

### ISSUE THREAD

**Issue by niekas** [LIKS/latex#3]
Neveikia Bakalaurinio ir kursinio darbų šablonų nuorodos.
-  [x] Problemai išspręsti reikia, remiantis magistrinio darbo šablonu sukurti bakalaurinio ir kursinio darbų šablonus. 
-  [x] Atnaujinti nuorodas į pateiktuosius šablonus.

**Comment by strazdas** [comment]
Šablonai sukurti ir nuorodos į juos patalpintos į latex.liks.lt puslapį.
